# @package _global_

env:
  name: CarRacing-v1
  demo: CarRacing-v1_100
  replay_mem: 1e6
  initial_mem: 5000
  eps_steps: 1e6
  eps_window: 10
  learn_steps: 1e6
  eval_interval: 5e3


expert:
  demos: 20
  subsample_freq: 1

eval:
  policy: 
  threshold:
  use_baselines: True
  eps: 10

agent:
  critic_target_update_frequency: 1000

train:
  batch: 64

q_net:
  _target_: agent.sac_models.ConvQCritic